language: go
go: '1.4'
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
script:
  - go test -coverprofile=parse.coverprofile -race -v ./parse
  - go test -coverprofile=main.coverprofile -race -v
after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
before_deploy:
- go get github.com/laher/goxc
- goxc -t
- 'goxc -pv=$TRAVIS_BRANCH -bc="linux windows darwin,amd64" -d=./dist/ -o="{{.Dest}}{{.PS}}{{.ExeName}}_{{.Version}}_{{.Os}}_{{.Arch}}{{.Ext}}" xc'
deploy:
  provider: releases
  api_key:
    secure: UdXkJy1HROgiZYQbFFqMipeFPI8Niqnk2Ek0IeHILvAhyGuzUAzvy08ogULJmnoaykNqXwvqplkQisDttz6pm9DRf1uV0RpIk6erX1ttSh/IXa8Q64B7+NobSDWciFeVRt0/ggaCKDHqJFPpnlKZ19sg0Bj/ubgC3NKZRyurkSpV5kXU/SRcL8wTTNhhnar53WZ534IpFJBWTReSki6wowgvg60tXLGf0ot4RUGW9dbzE775kR9oei1brI4DYmSgp2ggyNXsf8P7mfn9OrxZH6TfHpJHgbbm6YhYA5AaRKq6iJfnXk3TVOHq0qbdBIIzFaSChBEXOA+7UwKPyPL8SVLiozQ1FhxkTpFaUsajWajPqZltLRLjVcl6OQUxfCyo0v0fjJ34R/PFeV0yqWu0mx7J47hm+/tCngT6tXDrN+QBuWQ25wcuT5FciWfJcjfr7JKFX8YvWoAS0Bt0cUX8AEz7CS+9qoQV5IOCIcFE8cBrBxWS661fLHmSprV4+A5T1cawA0xpTTm4JXw0C8VWPCqHVfL4DdIaaS7uBtKgTmHZPiewrSwlhpk1TyQukOUcTxepkwrLhtSDJokeN7ualt/sTbexIEcgwrbemjNPqusSIcu1h+pO2aF7TQTOEsVh7dLyYhU/lGODnYRNRu83ry5kLmHqbHFr32stDN4GulE=
  file: ~/dist/*/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: Dtj0nWI/qtofy5NLW0XALWjxuEW4nV+IAv9PE+Yv7kZP0e2qKOqa2EurSSnYsnHWjjYIcZDr/EYZrcU/BwNRXj+KCnZ1BetvaZQFYnnFRkdu3Ys4QjzmYsJGkf4XHQKEEU7x5zvqiWeWctu2VcDt3JlGAKGPxLe+NVphbNhD/M4yJuLU6pR0JVUwCTrhkZHiHq501KzlzqSsQE3Qq9BqMV0+uT6YtFmYxfAp1n7x+NMZcw2xcig7ipw3O5MKfoRKrs02UHRo2WXuZI8UCvsCjAB6VuRKP/jpjx3KP65iqCRgGyZrOdGOPIsRsbKgWJnLytVXRNbXOO/tbQ63DzvSaduQbR71I5RQA84AZOb4QWv5obk8H4A2U+OF7CkX/K9yJFdQ23ef2oldACUFHGdvizD4HdWGxMnwCOZ9VjJtkTpiZlNAhkJYJD12QmbV0AMy3wK8mgDETMyXWQwz3GlTR+/aURUmn4o77ne5nCAnIcp/H1/MJHH5VmDa1A/aBE4HSkU9TOwRH4fLm34yDcColiRI5YYpG8eyZAXlohXF2ryC6yRMJArNTa3zdADMSqJV9aCrBgWO1W5v8s8tE1fveATqS6WzwZmZ4fZdKZ0Va9bTJWVPXTPT82FpClUwOVHoGyfW4fZTcdzhH1+C/7E4/N5z6LfXgolfAN30v5xd0kc=
  email: false
