caido-build:
  extends:
    file: common.yml
    service: caido
  command: npm run build -- --watch
serve:
  image: httpd:2.4
  volumes:
    - ../dist/:/usr/local/apache2/htdocs/
  ports:
    - "8000:80"
