language: node_js
node_js: '0.12'
script:
  - npm run lint
  - npm run test-selenium
  - npm run build
before_deploy: zip dist.zip dist/*
deploy:
  provider: releases
  api_key:
    secure: BS2wmoXNGjFUm4HsjmwifBvgmh00tJPe1g31JfMrTTJFINbgDayvR4Z/FC4rMaqc6TsB+cDxAEQXIjKKvphqpHrfSpwdsoMZMOtnLh0qdVW2w+Natin8cQnbCyRSbMBpeATW27UjlG5AJfFJ0Idqecr+0lSpvRXpnXwKRaNtgZOcpVv17SZHWYhp1MB/BxNoIxD0zdLuXzEbPdEeFEQwLvu29EZWnj1y6brSynVffN9xLMlEpcWYAJ/v0yntB4DcXd0SmcIOWiOsgKn/jeZpdkO24nOKwYAwmAFLezv/u/v3aDXopm+wT19Lt6ZF3TMi1WhGvleYOuwGbBAhN4bjGgVR2xc0AMcqI8k8XNXgUlGTMjG60VIJO2sqnrq9O9cG56gnCA0kN1763r0M32msBsMRQ5XIWrFoaSAM3RUxyF+VinuxxQ+H5ELWrydm8QZAgfNPZK7HbEjFyvX3B9aIX+93fPRkPr5zgRv+Zdx9XkGK+9YtySF6Az7vPgeSovPXzBBuFjzw6Oe0Oi2Z7XV4dGzF8/yzudEVYuQjHoM1vFY6G6+upTB8SFm1Xk0pvXPds07+GxKcgdLZpvD+2QYgpq/kHb0QRnhV9agUz4ax6AoESg7jXdlMZVg4RLlP80BHFyeODG03W5uGHpxUK6sKVGoGu62UdkAtJlb+cIgXfq8=
  file: dist.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: UdXkJy1HROgiZYQbFFqMipeFPI8Niqnk2Ek0IeHILvAhyGuzUAzvy08ogULJmnoaykNqXwvqplkQisDttz6pm9DRf1uV0RpIk6erX1ttSh/IXa8Q64B7+NobSDWciFeVRt0/ggaCKDHqJFPpnlKZ19sg0Bj/ubgC3NKZRyurkSpV5kXU/SRcL8wTTNhhnar53WZ534IpFJBWTReSki6wowgvg60tXLGf0ot4RUGW9dbzE775kR9oei1brI4DYmSgp2ggyNXsf8P7mfn9OrxZH6TfHpJHgbbm6YhYA5AaRKq6iJfnXk3TVOHq0qbdBIIzFaSChBEXOA+7UwKPyPL8SVLiozQ1FhxkTpFaUsajWajPqZltLRLjVcl6OQUxfCyo0v0fjJ34R/PFeV0yqWu0mx7J47hm+/tCngT6tXDrN+QBuWQ25wcuT5FciWfJcjfr7JKFX8YvWoAS0Bt0cUX8AEz7CS+9qoQV5IOCIcFE8cBrBxWS661fLHmSprV4+A5T1cawA0xpTTm4JXw0C8VWPCqHVfL4DdIaaS7uBtKgTmHZPiewrSwlhpk1TyQukOUcTxepkwrLhtSDJokeN7ualt/sTbexIEcgwrbemjNPqusSIcu1h+pO2aF7TQTOEsVh7dLyYhU/lGODnYRNRu83ry5kLmHqbHFr32stDN4GulE=
  email: false
env:
  global:
  - secure: IE+c7ItfgEkqbFSo8GtcMBc4NV9TDSJukhrhOfAWzbT61Arq0i2A65aJlRWmxq/s3A+PPvppNIIj/aPUdx0lQMluAALFp7dW8GPfR3XBA6yFOdFsT4tisQW9HiMAca+xSpVLpcJa/9RGepzFVzclTJNCKdpa39AhAcCn44ZlW2y0ltNJVwoUoUsdzKQOwejLZ9+/Qg8vUVNa6Z9XniBnNtM3LE0eLPHv7izTykoIZmVVo6YyZJC1IW6ifq6roJE7a9iJISQVWR/76rUfD8KghH9fKRjrJK6s9uB/sdPrU9WUo/geM+3rLuhsVZRYEKF4QNDGJn1HbRgoQy1KL8lyqdrnRrdgQKRpnE0LvHtRNHS1fEV3e8bZZQ0ZnX/Ubg2b/MMg8E3QoE0m8N6dyt3Sqzi82R1mIv7bhnE+zOVNAhTKTHsAKfnUUFhlsfTKdA0aF/fiVoqIB4aBZSYB2d7Yo0idCoF8yGtrsbl+zZGn3TcB3Wl2GSnjH8dw0CFWJ+fM8QYyJgBChxLZg5fYKNrCAG29cfNYG6xHy4B7ebjYkA3vADab9Kg0JSlMLr1UxqRnlDILo76HdZt74pmBg51uEPMSxhh2ymgbfOwDLfkviZjKeJl3hducWegJRYYP9OyO8ORAJBO8Ig2izIJHPfidd2uAwCV6LLa0i5AGJqZBSIc=
  - secure: cFofmr1Blknxaa3ZN48Z7ev5NpUH41PrO0+NYrG+xLgomCTh6yvA91XklNGaUrh1ZF7GoNQHdIVvfFdRX6ZK1/YdASnVoGTc/wnejo+VCKEWRVXrqso01cgh65bfJbZ8Sru9r1XZ6Vz1qLzR0S/Ov/1x7NRNU/VpBM8JxY5F8BYFjuFK3cQMO5sJLOveRXoY3NagUxnhiC6J7APK/PcAb4D9fB5ECeNQnwnwJ3qgpH3OgZvHREbSt98GgsBnVNs/l7oeOdZzTqBG+qhRqsLbd6Fvf9GkVdgK0X2UbVXqzye4f41iI7mTgIUI1yLAAOYC+IojoqpnIV7BG+RT/9D/UXQSF4DcjggcbY6rlwuuZAKS9XaSSnAZWy+z3gARYQ+AQUXiADkVjsHu00VsblKYJxKtpaj40e+CV2Y0mlY60PdlKyLLqagLGSz7Z84nuS33U9eoKyy7Gjs7mWsRr3Sazjjtj7YRJCtGF+bJ/A3bUViznG6RvqONAZGYneXpHHHZJIXZOZnP7tNkqsayxhjtuSovK/upNnL/jJUX3W6krz8f8dFLQNfkYetx2frG4wPlfxQHUvzO3Qk1aWsuY4a3hk0LFvu0X3n8T4XqCYEc5iPlG/9oiaX76Y+DMyozc6uS0pzq1OxwcLfZ+QYcdeOyoQ8/f6Z4QNg2CveeyfYCw/o=
addons:
  sauce_connect: true
